[build]
  # Build from project subdirectory - UPDATED
  base = "project"
  # Build command for Vite React app
  command = "npm run build"
  # Directory to publish (Vite builds to dist relative to base)
  publish = "dist"

[build.environment]
  # Use Node 18
  NODE_VERSION = "18"

# Cache control for HTML to prevent cold starts
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=86400, stale-while-revalidate=86400"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=86400, stale-while-revalidate=86400"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for other files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# SPA redirect (for React Router if used)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200